# Calculate the total revenue generated by two product categories in a store 
# Input: category1_revenue = np.array([500, 600, 700, 550]) 
# category2_revenue = np.array([450, 700, 800, 600])
# Output: Total Revenue: [ 950 1300 1500 1150] 

# Importing the NumPy library
import numpy as np

# Revenue for category 1
category1_revenue = np.array([500, 600, 700, 550])

# Revenue for category 2
category2_revenue = np.array([450, 700, 800, 600])

# Calculating total revenue for both categories
total_revenue = category1_revenue + category2_revenue

# Display the total revenue for each product category
print("Total revenue for each product category:", total_revenue)


# Output:

# Total revenue for each product category: [ 950 1300 1500 1150]
